import { createStore } from "jotai";
import type {
  Message,
  PeerState,
  Participant,
  WaitingParticipant,
} from "./atoms";
import {
  userAtom,
  roomAtom,
  roomTokenAtom,
  peerAtomFamily,
  peerIdsAtom,
  peerListAtom,
  localMediaAtom,
  chatAtom,
  participantsAtom,
  uiAtom,
  consentAtom,
  speakingPeersAtom,
  layoutModeAtom,
  selfViewModeAtom,
  pinnedParticipantsAtom,
  activeSpeakerAtom,
  reactionsEnabledAtom,
  roomLockedAtom,
  recordingAtom,
  recordingUploadsAtom,
  mutedByHostAtom,
  pinnedChatMessageAtom,
  captionsEnabledAtom,
  captionsAtom,
  audioOutputDeviceIdAtom,
  chatReactionsAtom,
  waitingRoomParticipantsAtom,
  waitingRoomPositionAtom,
  waitingTokenAtom,
  isWaitingAtom,
  waitingRoomEnabledAtom,
} from "./atoms";

export const store = createStore();

export {
  userAtom,
  roomAtom,
  roomTokenAtom,
  peerAtomFamily,
  peerIdsAtom,
  peerListAtom,
  localMediaAtom,
  chatAtom,
  participantsAtom,
  uiAtom,
  consentAtom,
  speakingPeersAtom,
  layoutModeAtom,
  selfViewModeAtom,
  pinnedParticipantsAtom,
  activeSpeakerAtom,
  reactionsEnabledAtom,
  roomLockedAtom,
  recordingAtom,
  recordingUploadsAtom,
  mutedByHostAtom,
  pinnedChatMessageAtom,
  captionsEnabledAtom,
  captionsAtom,
  audioOutputDeviceIdAtom,
  chatReactionsAtom,
  waitingRoomParticipantsAtom,
  waitingRoomPositionAtom,
  waitingTokenAtom,
  isWaitingAtom,
  waitingRoomEnabledAtom,
};

export type { Message, PeerState, Participant, WaitingParticipant };
